name: card_matching_game_by_ercan
description: A card-matching game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/easy.gif
    - assets/casual.gif
    - assets/tyler1-rage.gif
    - assets/veteran1.gif
    - assets/veteran2.gif

